AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'doc/**/*'
    - 'frontend/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Lint/HandleExceptions:
  Exclude:
    - 'config/unicorn/development.rb'
    - 'config/unicorn/local.rb'
    - 'config/unicorn/production.rb'

Metrics/AbcSize:
  Exclude:
    - 'db/**/*.rb'

Metrics/LineLength:
  Max: 160

Metrics/MethodLength:
  Exclude:
    - 'db/**/*.rb'

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExtraSpacing:
  Exclude:
    - 'db/migrate/*.rb'

Style/NumericLiterals:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: no_braces
  Exclude:
    - 'db/fixtures/*.rb'
