AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'doc/**/*'
    - 'frontend/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Lint/HandleExceptions:
  Exclude:
    - 'config/unicorn/*.rb'

Metrics/LineLength:
  Max: 120

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false
