AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'doc/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false
