== Tips
Hướng dẫn chung về nhưng `Gem` khác.

=== Decorator (Draper)

Gem tạo ra một lớp Presenter(Draper) nằm giữa view và model nhằm giảm thiểu các logic gây khó hiểu không cần thiết trong model và view.

==== Ví dụ
===== app/decorators/user_decorator.rb
[source, ruby]
----
class UserDecorator < Draper::Decorator
  delegate_all

  def full_name
    "#{first_name} #{last_name}"
  end
end
----

===== app/views/me/sample.html.erb
[source, ruby]
----
<h1><%= @user.full_name %></h1>
----

[NOTE]
Các thông tin khác của Draper có thể xem tại link Github dưới +
https://github.com/drapergem/draper

<<<

=== ActiveModelSerializers
Đây là library dùng để chuyển dạng dữ liệu của ActiveModel sang Serialize và chuyển sang JSON

==== Example
===== app/models/book.rb
[source, ruby]
----
class Book < ActiveRecord::Base
  belongs_to :publisher
  has_and_belongs_to_many :authors
end
----

===== app/serializers/book_serializer.rb
Chỉ định mục cần xuất bằng cách đặt tham số cho attributes
[source, ruby]
----
class BookSerializer < ActiveModel::Serializer
  attributes :id, :title, :price, :published_at, :publisher_id
end
----

===== app/controllers/books_controller.rb
[source, ruby]
----
def index
  @books = Book.all
  respond_to do |format|
    format.html
    format.json { render json: @books }
  end
end
----
Ngoài các chức năng đưa ra ở trên, còn có những chức năng thay đổi nội dung tuỳ vào điều kiện khác hoặc dựa trên Asscociation. Nếu cần thiết có thể xem tại trang chủ của Gem.


[NOTE]
Xem chi tiết về ActiveModelSerializers tại đường dẫn Github bên dưới +
https://github.com/rails-api/active_model_serializers
