if ENV['TARGET']
  source_files = Rake::FileList.new(ENV['TARGET'])
else
  source_files = Rake::FileList.new("./*.adoc") do |fl|
    fl.exclude("~*")
    fl.exclude("README.adoc")
    fl.exclude(%r{\Aasciidoctor-fopub/})
    fl.exclude(%r{\Avendor/})
  end
end

page_orientation = ENV['PAGE_ORIENTATION'] ? ENV['PAGE_ORIENTATION'] : 'portrait'

task default: :pdf

task pdf: source_files.ext('.pdf')
task html: source_files.ext('.html')

rule '.pdf' => '.adoc' do |t|
  dirname  = File.dirname t.source
  basename = File.basename t.source, '.adoc'
  xml_file = "#{dirname}/#{basename}.xml"
  docbook_xsl_path = "#{File.dirname(__FILE__)}/docbook-xsl-1pac"
  lang     = basename.match(/.+_en$/) ? 'en' : 'ja'
  open_cmd = ENV['OPEN'] ? "open out/#{t.name}" : ''

  sh %Q{
    bundle exec asciidoctor -a lang=#{lang} -b docbook -d book \
      -r asciidoctor-diagram -r asciidoctor-diagram-cacoo #{t.source} && \
    ./vendor/bin/fopub -t #{docbook_xsl_path} #{xml_file} \
      -param alignment left \
      -param page.orientation #{page_orientation} \
      -param body.font.family Meiryo \
      -param dingbat.font.family Meiryo \
      -param monospace.font.family Meiryo \
      -param title.color Teal \
      -param text.color dimgray \
      -param toc.section.depth 0 \
      -param sans.font.family Meiryo \
      -param title.font.family Meiryo && \
    mv -f #{t.name} out/#{t.name}
    rm -f #{xml_file}
    #{open_cmd}
  }
end

rule '.html' => '.adoc' do |t|
  sh "bundle exec asciidoctor --backend html5 -r asciidoctor-diagram -r asciidoctor-diagram-cacoo -o #{t.name} #{t.source} && open #{t.name}"
end

task :watch do
  target = ENV['TARGET'] || 'pdf'
  sh "bundle exec filewatcher '*.adoc' 'bundle exec rake #{target}'"
end
