if ENV['TARGET']
  source_files = Rake::FileList.new(ENV['TARGET'])
else
  source_files = Rake::FileList.new("./*.adoc") do |fl|
    fl.exclude("~*")
    fl.exclude("README.adoc")
    fl.exclude(%r{\Aasciidoctor-fopub/})
    fl.exclude(%r{\Avendor/})
  end
end

task default: :pdf

task pdf: source_files.ext('.pdf')
task html: source_files.ext('.html')

rule '.pdf' => '.adoc' do |t|
  dirname  = File.dirname t.source
  basename = File.basename t.source, '.adoc'
  xml_file = "#{dirname}/#{basename}.xml"
  docbook_xsl_path = "#{File.dirname(__FILE__)}/docbook-xsl-1pac"

  detected_lang = basename.match(/.+_(en|vi|ja)$/)
  lang = detected_lang.nil? ? 'ja' : detected_lang[1]
  fonts = {'vi' => 'Ricty',
           'ja' => 'Meiryo',
           'en' => 'Meiryo',
          }

  open_cmd = ENV['OPEN'] ? "open out/#{t.name}" : ''

  sh %Q{
    bundle exec asciidoctor -a lang=#{lang} -b docbook -d book \
      -r asciidoctor-diagram -r asciidoctor-diagram-cacoo #{t.source} && \
    ./vendor/bin/fopub -t #{docbook_xsl_path} #{xml_file} \
      -param alignment left \
      -param body.font.family #{fonts[lang]} \
      -param dingbat.font.family #{fonts[lang]} \
      -param monospace.font.family #{fonts[lang]} \
      -param title.color Teal \
      -param text.color dimgray \
      -param toc.section.depth 0 \
      -param sans.font.family #{fonts[lang]} \
      -param title.font.family #{fonts[lang]} && \
    mv -f #{t.name} out/#{t.name}
    rm -f #{xml_file}
    #{open_cmd}
  }
end

rule '.html' => '.adoc' do |t|
  sh "bundle exec asciidoctor --backend html5 -r asciidoctor-diagram -r asciidoctor-diagram-cacoo -o #{t.name} #{t.source} && open #{t.name}"
end

task :watch do
  target = ENV['TARGET'] || 'pdf'
  sh "bundle exec filewatcher '*.adoc' 'bundle exec rake #{target}'"
end
