AddModelVirtualAttributeCheck: { ignored_files: ['doc'] }
AlwaysAddDbIndexCheck: { ignored_files: ['doc'] }
#CheckSaveReturnValueCheck: { }
#CheckDestroyReturnValueCheck: { }
DefaultScopeIsEvilCheck: { ignored_files: ['doc'] }
DryBundlerInCapistranoCheck: { ignored_files: ['doc'] }
#HashSyntaxCheck: { }
IsolateSeedDataCheck: { ignored_files: ['doc'] }
KeepFindersOnTheirOwnModelCheck: { ignored_files: ['doc'] }
LawOfDemeterCheck: { ignored_files: ['doc'] }
#LongLineCheck: { max_line_length: 80 }
MoveCodeIntoControllerCheck: { ignored_files: ['doc'] }
MoveCodeIntoHelperCheck: { ignored_files: ['doc'], array_count: 3 }
MoveCodeIntoModelCheck: { ignored_files: ['doc'], use_count: 2 }
MoveFinderToNamedScopeCheck: { ignored_files: ['doc'] }
MoveModelLogicIntoModelCheck: { ignored_files: ['doc'], use_count: 4 }
NeedlessDeepNestingCheck: { ignored_files: ['doc'], nested_count: 2 }
NotRescueExceptionCheck: { ignored_files: ['doc'] }
NotUseDefaultRouteCheck: { ignored_files: ['doc'] }
NotUseTimeAgoInWordsCheck: { ignored_files: ['doc'] }
OveruseRouteCustomizationsCheck: { ignored_files: ['doc'], customize_count: 3 }
ProtectMassAssignmentCheck: { ignored_files: ['doc'] }
RemoveEmptyHelpersCheck: { ignored_files: ['doc'] }
#RemoveTabCheck: { }
RemoveTrailingWhitespaceCheck: { ignored_files: ['doc'] }
RemoveUnusedMethodsInControllersCheck: { ignored_files: ['doc'], except_methods: [] }
RemoveUnusedMethodsInHelpersCheck: { ignored_files: ['doc'], except_methods: [] }
RemoveUnusedMethodsInModelsCheck: { ignored_files: ['doc'], except_methods: [] }
ReplaceComplexCreationWithFactoryMethodCheck: { ignored_files: ['doc'], attribute_assignment_count: 2 }
ReplaceInstanceVariableWithLocalVariableCheck: { ignored_files: ['doc'] }
RestrictAutoGeneratedRoutesCheck: { ignored_files: ['doc'] }
SimplifyRenderInControllersCheck: { ignored_files: ['doc'] }
SimplifyRenderInViewsCheck: { ignored_files: ['doc'] }
#UseBeforeFilterCheck: { customize_count: 2 }
UseModelAssociationCheck: { ignored_files: ['doc'] }
UseMultipartAlternativeAsContentTypeOfEmailCheck: { ignored_files: ['doc'] }
#UseParenthesesInMethodDefCheck: { }
UseObserverCheck: { ignored_files: ['doc'] }
UseQueryAttributeCheck: { ignored_files: ['doc'] }
UseSayWithTimeInMigrationsCheck: { ignored_files: ['doc'] }
UseScopeAccessCheck: { ignored_files: ['doc'] }
UseTurboSprocketsRails3Check: { ignored_files: ['doc'] }
